# Generated by Django 6.1 on 2026-08-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('FULLSTACK', 'Full Stack'), ('MOBILE', 'Mobile'), ('API', 'API / Integration'), ('UIUX', 'UI/UX Design'), ('INFRA', 'Infrastructure / DevOps')], default='FULLSTACK', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
