# Generated by Django 6.1 on 2026-08-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_project_type_project_tech_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
